"""adding name and email optional to buyers and sellers

Revision ID: 1505546ed773
Revises: 40d3180c8aff
Create Date: 2025-01-09 23:45:18.225209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1505546ed773'
down_revision: Union[str, None] = '40d3180c8aff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buyers', sa.Column('name', sa.String(), nullable=False))
    op.add_column('buyers', sa.Column('email', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'buyers', ['email'])
    op.add_column('sellers', sa.Column('name', sa.String(), nullable=False))
    op.add_column('sellers', sa.Column('email', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'sellers', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sellers', type_='unique')
    op.drop_column('sellers', 'email')
    op.drop_column('sellers', 'name')
    op.drop_constraint(None, 'buyers', type_='unique')
    op.drop_column('buyers', 'email')
    op.drop_column('buyers', 'name')
    # ### end Alembic commands ###
