"""making user_id optional and nullable for standalone buyers and sellers

Revision ID: 2891bb5de4e2
Revises: 1505546ed773
Create Date: 2025-01-09 23:53:41.342914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2891bb5de4e2'
down_revision: Union[str, None] = '1505546ed773'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('buyers', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('sellers', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sellers', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('buyers', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
