"""addint teams column in users

Revision ID: 40d3180c8aff
Revises: 2f7c0f0d6411
Create Date: 2025-01-05 12:00:39.323689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40d3180c8aff'
down_revision: Union[str, None] = '2f7c0f0d6411'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('team_names', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'team_names')
    # ### end Alembic commands ###
