"""fixing role of user

Revision ID: 472630afe4c1
Revises: 47dabdc812d0
Create Date: 2025-03-04 17:54:13.371452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '472630afe4c1'
down_revision: Union[str, None] = '47dabdc812d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

old_enum_type = postgresql.ENUM('USER', 'BUYER', 'SELLER', 'BOTH', name='userrole')

# Define the new ENUM type (with added values)
new_enum_type = postgresql.ENUM('USER', 'BUYER', 'SELLER', 'USERSELLER', 'USERBUYER', 'ALL', name='userrole')

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    new_enum_type.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('role_new', sa.ARRAY(new_enum_type), nullable=True))
    op.drop_column('users', 'role')
    op.alter_column('users', 'role_new', new_column_name='role')
    op.execute("DROP TYPE userrole CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    old_enum_type.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('role_old', sa.ARRAY(old_enum_type), nullable=True))
    op.drop_column('users', 'role')
    op.alter_column('users', 'role_old', new_column_name='role')
    op.execute("DROP TYPE userrole CASCADE")
    # ### end Alembic commands ###
