"""fixing role of user

Revision ID: 47dabdc812d0
Revises: cfeb8a752026
Create Date: 2025-03-04 17:44:56.208531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '47dabdc812d0'
down_revision: Union[str, None] = 'cfeb8a752026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('USER', 'BUYER', 'SELLER', 'BOTH', name='userrole'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('USER', 'BUYER', 'SELLER', 'BOTH', name='userrole'),
               nullable=False)
    # ### end Alembic commands ###
