"""adding columns to chat-related orms

Revision ID: 4e78804b38ec
Revises: 65d501ebd0c0
Create Date: 2025-01-17 17:38:51.413316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e78804b38ec'
down_revision: Union[str, None] = '65d501ebd0c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_members', sa.Column('joined_at', sa.DateTime(), nullable=False))
    op.add_column('chats', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('chats', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'is_deleted')
    op.drop_column('chats', 'updated_at')
    op.drop_column('chat_members', 'joined_at')
    # ### end Alembic commands ###
