"""ditto

Revision ID: 5b5b38ad3f75
Revises: 65274d85a254
Create Date: 2025-01-01 04:22:53.344350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b5b38ad3f75'
down_revision: Union[str, None] = '65274d85a254'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users',
        'created_at',
        server_default=sa.func.now(),  # Use database default
        existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users',
        'created_at',
        server_default=None,
        existing_nullable=False
    )
    # ### end Alembic commands ###
