"""fixing comments model

Revision ID: 5d518bdaa3e8
Revises: 8dc92b12b2d3
Create Date: 2025-01-01 03:45:15.005066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d518bdaa3e8'
down_revision: Union[str, None] = '8dc92b12b2d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_username_fkey', 'comments', type_='foreignkey')
    op.drop_column('comments', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('comments_username_fkey', 'comments', 'users', ['username'], ['username'])
    # ### end Alembic commands ###
