"""Add default to Users.created_at

Revision ID: 65274d85a254
Revises: a1a4532f1768
Create Date: 2025-01-01 04:18:27.165233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65274d85a254'
down_revision: Union[str, None] = 'a1a4532f1768'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users',
        'created_at',
        server_default=sa.func.now(),  # Use database default
        existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users',
        'created_at',
        server_default=None,
        existing_nullable=False
    )
    # ### end Alembic commands ###
