"""adding role in column

Revision ID: 7baeae8cca07
Revises: 472630afe4c1
Create Date: 2025-03-04 18:22:39.115951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7baeae8cca07'
down_revision: Union[str, None] = '472630afe4c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

new_enum_type = postgresql.ENUM('USER', 'BUYER', 'SELLER', 'USERSELLER', 'USERBUYER', 'ALL', name='userrole')
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    new_enum_type.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('role', sa.Enum('USER', 'BUYER', 'SELLER', 'USERSELLER', 'USERBUYER', 'ALL', name='userrole'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    new_enum_type.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
