"""fixing team members model

Revision ID: 97c24a86b0a5
Revises: 5d518bdaa3e8
Create Date: 2025-01-01 03:47:32.131554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97c24a86b0a5'
down_revision: Union[str, None] = '5d518bdaa3e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('team_members_username_key', 'team_members', type_='unique')
    op.drop_constraint('team_members_username_fkey', 'team_members', type_='foreignkey')
    op.drop_column('team_members', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_members', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('team_members_username_fkey', 'team_members', 'users', ['username'], ['username'])
    op.create_unique_constraint('team_members_username_key', 'team_members', ['username'])
    # ### end Alembic commands ###
