"""adding column to chat

Revision ID: 9e83deb26b54
Revises: 4e78804b38ec
Create Date: 2025-01-18 13:50:29.484909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e83deb26b54'
down_revision: Union[str, None] = '4e78804b38ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE chattype AS ENUM ('private', 'group')")
    op.add_column('chats', sa.Column('owner_id', sa.UUID(), nullable=False))
    op.add_column('chats', sa.Column('chat_type', sa.Enum('private', 'group', name='chattype'), nullable=False, server_default='private'))
    op.create_foreign_key(None, 'chats', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.execute("DROP TYPE chattype")
    op.drop_column('chats', 'chat_type')
    op.drop_column('chats', 'owner_id')
    # ### end Alembic commands ###
