"""fixing user orm model

Revision ID: a1a4532f1768
Revises: 97c24a86b0a5
Create Date: 2025-01-01 03:55:42.504237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1a4532f1768'
down_revision: Union[str, None] = '97c24a86b0a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fanArts_username_fkey', 'fanArts', type_='foreignkey')
    op.drop_column('fanArts', 'username')
    op.add_column('messages', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('messages', sa.Column('is_sender', sa.Boolean(), nullable=False))
    op.drop_constraint('messages_sender_id_fkey', 'messages', type_='foreignkey')
    op.drop_constraint('messages_receiver_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['user_id'], ['id'])
    op.drop_column('messages', 'sender_id')
    op.drop_column('messages', 'receiver_id')
    op.drop_constraint('posts_username_fkey', 'posts', type_='foreignkey')
    op.drop_column('posts', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('posts_username_fkey', 'posts', 'users', ['username'], ['username'])
    op.add_column('messages', sa.Column('receiver_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('sender_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_receiver_id_fkey', 'messages', 'users', ['receiver_id'], ['id'])
    op.create_foreign_key('messages_sender_id_fkey', 'messages', 'users', ['sender_id'], ['id'])
    op.drop_column('messages', 'is_sender')
    op.drop_column('messages', 'user_id')
    op.add_column('fanArts', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('fanArts_username_fkey', 'fanArts', 'users', ['username'], ['username'])
    # ### end Alembic commands ###
