"""gave default to role attribute

Revision ID: cfeb8a752026
Revises: c63d65eba696
Create Date: 2025-03-04 16:38:13.474695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cfeb8a752026'
down_revision: Union[str, None] = 'c63d65eba696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('USER', 'BUYER', 'SELLER', 'BOTH', name='userrole'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('USER', 'BUYER', 'SELLER', 'BOTH', name='userrole'),
               nullable=True)
    # ### end Alembic commands ###
