"""fixing foriengn keys issues

Revision ID: fa0de079dcfc
Revises: 85cf2c789f79
Create Date: 2024-12-31 16:39:40.927064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa0de079dcfc'
down_revision: Union[str, None] = '85cf2c789f79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
